services:
  timescaledb:
    image: timescale/timescaledb:2.13.1-pg14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lighthouse-network

  temporal-postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5433:5432"
    volumes:
      - temporal_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal -d temporal"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lighthouse-network

  temporal:
    image: temporalio/auto-setup:1.22.3
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development.yaml
    ports:
      - "7233:7233"
    depends_on:
      temporal-postgresql:
        condition: service_healthy
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig
    networks:
      - lighthouse-network
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  temporal-ui:
    image: temporalio/ui:2.21.3
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal
    networks:
      - lighthouse-network
      
  worker:
    build:
      context: . # Build using Dockerfile in the current directory
    # Use container_name for easier local identification (optional)
    container_name: lighthouse-worker-dev
    command: ["npx", "nodemon", "src/worker.ts"] 
    volumes:
      # Mount local source code into the container
      # Needed for nodemon to detect changes
      - ./src:/app/src
      # Mount tsconfig.json
      - ./tsconfig.json:/app/tsconfig.json
      # Use anonymous volume to prevent local node_modules overwriting container's
      - /app/node_modules
    environment:
      # Enable debugging
      - DEBUG=temporal*,workflow*
      # Connect to infra services using their service names
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=postgres
      # Read DB name and password from local .env file
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Add other dev-specific env vars if needed
      - NODE_ENV=development
    depends_on:
      - temporal
      - timescaledb
    networks:
      - lighthouse-network
    # Add stdin_open/tty if needed for specific debugging, usually not for workers
    # stdin_open: true
    # tty: true

  scheduler:
    build:
      context: . # Build using Dockerfile in the current directory
    container_name: lighthouse-scheduler-dev # Optional
    command: ["npx", "nodemon", "src/scheduler.ts"]
    volumes:
      # Mount local source code
      - ./src:/app/src
      # Mount tsconfig.json
      - ./tsconfig.json:/app/tsconfig.json
      # Use anonymous volume for node_modules
      - /app/node_modules
    environment:
      # Enable debugging
      - DEBUG=temporal*,workflow*
      # Connect to infra services using their service names
      - TEMPORAL_ADDRESS=temporal:7233
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=postgres
      # Read DB name and password from local .env file
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Add other dev-specific env vars if needed
      - NODE_ENV=development
    depends_on:
      - temporal
      - timescaledb
    networks:
      - lighthouse-network

networks:
  lighthouse-network:
    driver: bridge

volumes:
  timescale_data:
  temporal_postgres_data:
